imports:
    - { resource: config.yml }

#doctrine:
#    dbal:
#        connections:
#            default:
#                host: 10.10.18.1
#                port: 3306
#                dbname: pimcore
#                user: TS-8wiOPVF9AodKm

parameters:
    main.domain       : "ngl-bizdev.test.vitapublic.de"
    main.js.minified.enable   : true
    main.css.minified.enable  : true
    RegisterUrl       : "https://ngl-bizdev.test.vitapublic.de/ess-authentication-mvc-application/registration?redirect_uri=https://ngl-new.test.vitapublic.de&response_type=code&scope=openid&client_id=57HUAFHMJ7aUomZwoUABAisbTIQa&state=eyJob3N0VXJsIjoiIiwiaGFzaHJvdXRlciI6IiMiLCJ0eXBlIjoicmVkaXJlY3QifQ=="
    BootstrapperUrl   : "https://cdn-ngl-bizdev.test.vitapublic.de/bootstrapper/57HUAFHMJ7aUomZwoUABAisbTIQa.min.js"
    piwik.enable      : true
    piwik.hostname    : "tracking-bizdev.test.vitapublic.de"
    piwik.siteId      : 1
    piwik.jsFilePath  : "piwik.48028d63564a63e6ec32782aa54d30c5.js"
    googleAnalytics.enable      : true
    googleAnalytics.hostname    : "https://www.googletagmanager.com/gtag/js?id=%googleAnalytics.siteId%"
    googleAnalytics.siteId      : "UA-122860046-3"
    webappProfileUrl  : "https://ngl-bizdev.test.vitapublic.de/player/X"

    fontUrlRoboto         : "https://cdn-ngl-bizdev.test.vitapublic.de/ngl-fonts/roboto/v1/Roboto.css"
    fontUrlTitilliumWeb   : "https://cdn-ngl-bizdev.test.vitapublic.de/ngl-fonts/titillium_web/v1/Titillium_Web.css"
    fontUrlNglIconfont    : "https://cdn-ngl-bizdev.test.vitapublic.de/fonts/ngl-iconfont.css"
    fontUrlFontAwesome    : "https://cdn-ngl-bizdev.test.vitapublic.de/fonts/font-awesome.css"

    jsconfigAuthEndpoint                        : "https://ngl-bizdev.test.vitapublic.de/ess-authentication-mvc-application"
    jsconfigTokenEndpoint                       : "https://ngl-bizdev.test.vitapublic.de/oauth2/token"
    jsconfigTournamentEndpoint                  : "https://api-ngl-bizdev.test.vitapublic.de/ess-tournament-service"
    jsconfigAssetEndpoint                       : "https://cdn-ngl-bizdev.test.vitapublic.de"
    jsconfigProfileEndpoint                     : "https://ngl-bizdev.test.vitapublic.de"

    jsconfigAppUrl                              : "https://ngl-bizdev.test.vitapublic.de/"

    jsconfigApiVersion                          : "application/json"
    jsconfigClientId                            : "57HUAFHMJ7aUomZwoUABAisbTIQa"

    jsconfigCookieNamePageReload                : "ngl_page_reload"
    jsconfigCookieNameIdTokenOrganizer          : "ngl_organizer"
    jsconfigCookieNameIdTokenOrganizerExpires   : "ngl_organizer_exp"
    jsconfigCookieNameIdTokenUser               : "ngl_user"
    jsconfigCookieNameIdTokenUserExpires        : "ngl_user_exp"
    jsconfigCookieNameRefreshTokenUser          : "ngl_refresh"
    jsconfigCookieNameAccessTokenUser           : "ngl_access"
    jsconfigCookieNameCookieAgreement           : "ngl_cookie_agreement"
    jsconfigCookieNameGamezNotification         : "ngl_cookie_gamez_notification"
    jsconfigCookieNameDisableAnalytics          : "ngl_cookie_disable_analytics"
    jsconfigDefaultGameRankingRequestParameter  : "2?platform=playstation4&gamemode=classic"

    jsconfigDebug                               : true

    essApiClient.baseUrl  : "https://api-ngl-bizdev.test.vitapublic.de"
    essApiClient.apiKey   : "eyJ4NXQiOiJZekEyT0RJd01XVTNOV0ZoTURkbVl6TTFaamd5WkRobU5qUTFPRFU0WVRFeU5qa3lZelZrWWciLCJraWQiOiJkMGVjNTE0YTMyYjZmODhjMGFiZDEyYTI4NDA2OTliZGQzZGViYTlkIiwiYWxnIjoiUlMyNTYifQ.eyJhdF9oYXNoIjoiQWJPS1h1TUtLZ255bWNnZkhnaW5qdyIsImFjciI6InVybjptYWNlOmluY29tbW9uOmlhcDpzaWx2ZXIiLCJhdWQiOlsiTnNWWlNMOFJxOGJmb1pwOG9PUUszbzBhS1VBYSJdLCJyb2xlIjoiSW50ZXJuYWwvZXZlcnlvbmUsQXBwbGljYXRpb24vZXNzLWNtcyIsImF6cCI6Ik5zVlpTTDhScThiZm9acDhvT1FLM28wYUtVQWEiLCJzY29wZSI6Im9wZW5pZCIsIm5pY2tuYW1lIjoiZXNzLWNtcy1hbm9ueW1vdXMiLCJpc3MiOiJodHRwczovL25nbC1uZXcudGVzdC52aXRhcHVibGljLmRlL29hdXRoMi90b2tlbiIsImV4cCI6MTYwMTY2MjIxNiwiaWF0IjoxNTI3NDQ0NDM0LCJlbWFpbCI6ImVzcy1jbXMtYW5vbnltb3VzQHdzMDk5LnZpdGFwdWJsaWMuZGUifQ.kwPTlLAcUU5wZl4kSYD0oJDKGUq5sR5sXu9LEBOmcF9l9ucT7oN7bif71iCIOsH04qAT4BWP1e_G4Q3RWhLkbqE4v0y6B8mVOkowYVh7T8rfo9rlCT6qTfAd3wLzjaX6fDf2CxwJGvesK1br4HlBaIWFv_OmWboTO6iiMD6a7jJIZu1B-JzxPueVQ_bLI8Lr0GxWIiok-Da54WkGaWmcmsp3f6u6ZIALL47RHhZyYhZbuu2DOADuxd7WYI6zZGwQAPVRKK6mMKyJuhwABNfTt_T2RZgN_scI-BtXu3SmgQYq9ALRz7QyrEIM_QKHI17DyuS6eRkbAD14CPAs5Djs5g"
    
    amaApiClient.baseUrl  : "https://ama-back.test.vitapublic.de"
    amaApiClient.apiKey   : "eyJ4NXQiOiJOakUyWWpCbVpqRTFObUZrWkRSaFltVXpNelprTVdWak16WXlNRE0xTldZMllqVTRZak14TnciLCJraWQiOiJkMGVjNTE0YTMyYjZmODhjMGFiZDEyYTI4NDA2OTliZGQzZGViYTlkIiwiYWxnIjoiUlMyNTYifQ.eyJhdF9oYXNoIjoiT09rcmt6VXl4QUJMVTJ1MTF1X1A3dyIsImFjciI6InVybjptYWNlOmluY29tbW9uOmlhcDpzaWx2ZXIiLCJzdWIiOiJ0ZXN0LWFwaS10by1hbWFAY2FyYm9uLnN1cGVyIiwiYXVkIjpbIlFYQmo2OXFCNkpPSlZWaWRCRVN2T3o0OGVQOGEiXSwicm9sZSI6IkludGVybmFsL2V2ZXJ5b25lLEFwcGxpY2F0aW9uL2Vzcy1zdXBlci1hZG1pbiIsImF6cCI6IlFYQmo2OXFCNkpPSlZWaWRCRVN2T3o0OGVQOGEiLCJzY29wZSI6Im9wZW5pZCIsIm5pY2tuYW1lIjoidGVzdEFwaVRvQW1hIiwiaXNzIjoiaHR0cHM6Ly9uZ2wtbmV3LnRlc3Qudml0YXB1YmxpYy5kZS9vYXV0aDIvdG9rZW4iLCJleHAiOjE2MDE1MTA0MDAsImlhdCI6MTUxMjE0NjMyMywiZW1haWwiOiJ0ZXN0QXBpVG9BbWFAdGVzdGluZzAxLnZpdGFwdWJsaWMuZGUifQ.Z2jw_VW4cCsMR3dZMdzCR4oW1TCRSQzL7XwolPOix2Mx9DavEKC4qnKL7X9L8Yy3W7glWf9kRI670blRCeMD4-_RGiczJQp75mU1nuT5oSDBCysturbBAm_urDrAIgNL8V8O1FVsHsxlhZKKKb2q6sJ7h8fek2t-6NqQe9E9hW4mEZr-3uIwQ66gaT31Ls3IkjynA4mlEpubElRIZwhQJ_3iZvPDUWLGaQoNG1OQKOsRiVeWxjKYbHzQ7BF7GSIAKUzxFg2aFB_JSP-8gJ4ZdBGWEL9x3hEnhqkdtFJaxoJxttsll-vMwYRMNfogYOAiP4leEpT0zSToxnh1qzw9Ew"

    proClubHelper.proClubBaseUrl    : "https://ngl-bizdev.test.vitapublic.de/proclub/"
    proClubHelper.mediaServerBaseUrl: "https://ama-media.test.vitapublic.de"
    proClubHelper.mediaServerTenant: "amateur"
    proClubHelper.parentOrganizationId: 100326
    proClubHelper.defaultLeagueId: 100370
    proClubHelper.organizerToPlatfromMapping  :
        100330: PLAYSTATION4
        100071: XBOX
        100075: PC
    # Game ID only for FIFA18 in tournament system!
    proClubHelper.organizerToGameIdMapping  :
        100330: 5
        100071: 5
        100075: 5

    essApiHelper.cdnBaseUrl : "https://cdn-ngl-bizdev.test.vitapublic.de"

pimcore:
### REDIS CACHE
    cache:
        pools:
            redis:
                enabled: true
                connection:
                    server: 10.10.18.1
                    database: 5
    documents:
            tags:
                map:
                    datetime: \AppBundle\Model\Document\Tag\DateTime

monolog:
    handlers:
        main:
            type:   stream
            path:   '%kernel.logs_dir%/%kernel.environment%.log'
            level:  info