pimcore_install:
    parameters:
        profile: vitapublic/basic-bundle
        database_credentials:
            user:                 admin
            password:             admin
            dbname:               pimcore_01
            
            # env variables can be directly read with the %env() syntax
            # see https://symfony.com/blog/new-in-symfony-3-2-runtime-environment-variables
            host:                localhost
            port:                3301